import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const originalWarn = console.warn.bind(console.warn);
  console.warn = (msg, ...params) => {
    if (
      msg.includes('Using supabase.auth.getSession() is potentially insecure')
    ) {
      return;
    }
    originalWarn(msg, ...params);
  };
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
