const brands = [
    { linecode: "MOT", brand: "Motorcraft"},
    { linecode: "ACD", brand: "ACDELCO"},
    { linecode: "ALL", brand: "Alliant Power"},
    { linecode: "AMB", brand: "AMBAC International"},
    { linecode: "ARP", brand: "ARP Headstuds"},
    { linecode: "BAL", brand: "Baldwin Filters"},
    { linecode: "CLA", brand: "Stanadyne"},
    { linecode: "BOS", brand: "Bosch"},
    { linecode: "BOR", brand: "Borg Warner"},
    { linecode: "HRT", brand: "Hartridge Test Equipment"},
    { linecode: "REM", brand: "Delco Remy"},
    { linecode: "CUM", brand: "Cummins"},
    { linecode: "CON", brand: "Contennial Batteries"},
    { linecode: "STD", brand: "Stanadyne"},
    { linecode: "DEL", brand: "Delphi"},
    { linecode: "DEN", brand: "Denso"},
    { linecode: "DOR", brand: "Dorman"},
    { linecode: "FPD", brand: "FP Diesel - Felpro"},
    { linecode: "GAR", brand: "Garret"},
    { linecode: "GAT", brand: "Gates"},
    { linecode: "HOR", brand: "Horton"},
    { linecode: "IMB", brand: "Interstate McBee"},
    { linecode: "KYS", brand: "KYSOR-AC"},
    { linecode: "LUB", brand: "Luber-Finer"},
    { linecode: "MAH", brand: "Mahle"},
    { linecode: "MAX", brand: "Maxiforce"},
    { linecode: "MSP", brand: "MSP Diesel Solutions"},
    { linecode: "NPD", brand: "Nippon Diesel"},
    { linecode: "OTC", brand: "OTC"},
    { linecode: "PPT", brand: "Pure Power Tech"},
    { linecode: "RAC", brand: "Racor"},
    { linecode: "RAY", brand: "Raybestos"},
    { linecode: "REA", brand: "Reach"},
    { linecode: "SUN", brand: "Sunair"},
    { linecode: "YAN", brand: "Yanmar"},
    { linecode: "ZEX", brand: "Zexel"},
    { linecode: "GPN", brand: "Global Parts Network"},
    { linecode: "GRZ", brand: "Grizzly"},
    { linecode: "HOL", brand: "Holset"},
    { linecode: "INT", brand: "Volunteer International"},
    { linecode: "LUC", brand: "LUCAS"},
    { linecode: "PAI", brand: "PAI"},
    { linecode: "CHM", brand: "Chemicals and fluids"},
    { linecode: "WOG", brand: "Peaker Services"},
    { linecode: "RWR", brand: "Roadwarrior"},
    { linecode: "WAL", brand: "Walker Products"}
]

export default brands